language: node_js
env:
  - SESSION_SECRET=secret
services:
  - mysql
before_install:
  - mysql cityglide-test < test/cityglide-test.sql
cache:
  directories:
    - node_modules
branches:
  only:
    - develop
    - master
notifications:
  email: false
node_js:
  - '7'
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test
